### PR TITLE
Added: php8 union types, constructor property AND param with default null

### PR DESCRIPTION
**Pull request by tianyiw2013**
## php8 Union types #150 

```php
/**
 * PHP8 union types
 * 
 * @param int|bool $arg
 * @return int|bool
 */
function getPHP8UnionTypes(int|bool $arg): int|bool
{
}
```

## php8 Constructor with property #156 
```php
  /**
   * php8 Constructor with property
   *
   * @param [type] $arg1
   * @param int $arg2
   * @param int|null $arg3
   */
  function __construct(public $arg1, protected int $arg2, PriVate ?int $arg3)
  {
  }
```

##  Param with default null
```php
/**
 * Param with default null
 *
 * @param int|null $arg
 * @return void
 */
function paramDefaultNull(int $arg = null)
{
}

/**
 * Param with mixed and default null
 *
 * @param mixed $arg
 * @return void
 */
function paramMixedDefaultNull(mixed $arg = null)
{
}
```

## compatibility with param syntax error
```php
  /**
   * compatibility with param syntax error
   *
   * @param int $arg
   * @param syntax error 
   * @param syntax_error 
   * @param int $arg2
   * @param mixed $arg3
   * @return void
   */
  function compatibilitySyntaxError(syntax error int $arg, syntax error, syntax_error, int| $arg2, || $arg3)
  {
  }
```

### CODE REVIEW

**Comment by tianyiw2013** [comment]
The author(@neild3r) may be very busy recently. I build a vsix extension file, which can be used temporarily by friends in need.

[php-docblocker-2.1.1.zip](https://github.com/neild3r/vscode-php-docblocker/files/6499673/php-docblocker-2.1.1.zip)

**Comment by tianyiw2013** [comment]
I fixed it, [here](https://github.com/neild3r/vscode-php-docblocker/pull/162#issuecomment-842976125)

**Review by runthis — APPROVED** [review]

**Comment by tianyiw2013** [comment]
build the latest vsix extension file.
[php-docblocker-2.1.2.zip](https://github.com/neild3r/vscode-php-docblocker/files/6512647/php-docblocker-2.1.2.zip)

**Comment by tianyiw2013** [comment]
Sorry, the author's follow-up is too slow, I temporarily close the request, I temporarily released the vscode extension using my branch and named it `php-docblocker`.If the author can continue to follow up, I will remove my version from the vscoed market.
Thank you.

**Comment by tianyiw2013** [comment]
My branch version: https://marketplace.visualstudio.com/items?itemName=tianyiw.php-docblocker2

**Comment by harpreetsb** [comment]
thank you so much @tianyiw2013

**Pull request closed without merging**
