### PR TITLE
let the user decide wether he wants to use `bool` instead of `boolean`

### PR DESCRIPTION
**Pull request by jens1o**

### CODE REVIEW

**Comment by jens1o** [comment]
When the general change is good to you, I'll create the tests if you want to.

**Comment by neild3r** [comment]
We should probably do int/integer as well and say use short names instead of long names option instead of specifically for booleans, in terms of testing we could update the unit tests to support passing in config options

**Comment by jens1o** [comment]
I like that idea. I'll do it asap. Could you update the units test, please? (I'm not very talented with ts at all.)

**Comment by jens1o** [comment]
Closing this in favor of an upcoming pr.

**Pull request closed without merging**
