### PR TITLE
Feature | Implement settings for aligning params and return statements

### PR DESCRIPTION
**Pull request by MGApcDev**
Related: #37 

Added 3 options:
- `php-docblocker.alignParams` , default `false`
- `php-docblocker.alignReturn` , default `false`
- `php-docblocker.alignTrimExtraSpaces` , default `false`

With alignParams: true
Screenshot 2021-05-09 at 11 39 55

With alignParams: true and alignReturn: true
Screenshot 2021-05-09 at 11 39 14

With alignParams: true and alignReturn: true and alignTrimExtraSpaces: true
Screenshot 2021-08-15 at 19 50 46

- The options are disabled to not affect existing users.
- The alignment is limited to spaces only.

<s>I was not able to run the test suite locally without issue, so I'm not quite sure how to write a tests to check for the new alignment. If you feel there is a need for additional tests, let me know and I'll see what I can do.</s>

I'm also very open for changes to code structure and naming conventions.

### CODE REVIEW

**Comment by shivapoudel** [comment]
@neild3r Can you review this PR seems fruitful PR?

**Comment by neild3r** [comment]
I will get round to it as soon as I can I've had an initial scan and will feedback soon

**Comment by neild3r** [comment]
In general all looks OK. It's a shame to add more mess to that already messy function but most of that is my bad.

I'm not sure we need the white space after the variable names lining up. What's the reason for this?

In my eyes ideally we'd get rid of the white space after the variable names, move spacing length calculation out to another function then the whole thing becomes a bit cleaner and simpler.

**Comment by MGApcDev** [comment]
@neild3r 
> I'm not sure we need the white space after the variable names lining up. What's the reason for this?

I think this a bit of preference, so you could go with or without the extra space.
Initially I didn't have the extra space, but in practice I just found it to make more sense, with the extra space you can write your comment straight away. The argument to not have the extra space is that "Without the comment, you will have extra spaces that should be trimmed", that makes sense, but there would still be too many spaces other places.

Screenshot 2021-08-10 205251

This could also be an additional setting, but I don't know if it gets too bloaty.

 ---

> ..., move spacing length calculation out to another function or even a little class then the whole thing becomes a bit cleaner and simpler. We could effectively assign the spacing out to a variable which we always use and wether that is 1 or many spaces depends on the config.

I think those changes sound good, should I give it a shot, or do you have a clear idea of how you would do it?
I was also thinking how to make this work for tab users, but the logic could get a bit complicated with different definitions of the tab size (so I skipped it).

**Comment by neild3r** [comment]
I can try if you like but I'm also happy for you to have a go. I see your point about comments after but perhaps that's one for having the optional description after the param definition which I think is a different set of changes (that I think has been requested) so lets look at that in a different change set and get this in without.

**Comment by shivapoudel** [comment]
@neild3r This fork adapts the description set so you can look on that PR. Additionally, there are many great changes too!
https://github.com/tianyiw2013/vscode-php-docblocker

**Comment by MGApcDev** [comment]
@neild3r I'll give it a go.

I think you made a good point about the extra spaces.
For some people the params will give enough information, so they don't need the extra spaces.
I'll think I'll add a setting to trim the additional spaces.

**Comment by shivapoudel** [comment]
@MGApcDev Does this also resolves this ticket https://github.com/neild3r/vscode-php-docblocker/issues/164

**Comment by MGApcDev** [comment]
@neild3r 

There we go, I separated some of the logic into other functions, so it looks a bit cleaner.
Added a setting:
- `php-docblocker.alignTrimExtraSpaces` , default `false`

With alignParams: true and alignReturn: true and alignTrimExtraSpaces: true
Screenshot 2021-08-15 at 19 50 46

- This way people who frequently write comments, can directly do that without added spaces manually.
- And people who only write the param types don't have any extra spaces they need to trim.

I also pulled the latests changes from `master` so everything should be up-to-date.
And changed package-lock to version 2.3.0

Check if it looks good.

**Comment by MGApcDev** [comment]
@shivapoudel 

> @MGApcDev Does this PR resolves this ticket #164

No, I don't think so.
It might just be me, but I don't understand what is expected of the ticket.

**Comment by neild3r** [comment]
It doesn't but I think it should as we are getting close to it. 

I don't think we should introduce the config option you've proposed here but instead we may as well go the whole hog and add a config option to add a message placeholder to parameters then instead of having blank spaces at the end we have tab stops to messages. Then we can activate the spaces at the end based on if that feature is turned on or not.

Does that make sense? I'm happy to take this over and get it over the line. I'm just finishing up some additions on union types then I can help get this over the line

**Comment by man-dwarf** [comment]
I see, that could be useful to people without a mouse and the option would be easier to understand. 

Yeah I think at this point it makes sense for you to take over. Change anything you need to.

**Comment by neild3r** [comment]
OK @man-dwarf this is now passing tests

**Comment by shivapoudel** [comment]
@neild3r Eagerly waiting for this feature in the release. When the release is supposed to be :)

**Comment by neild3r** [comment]
@shivapoudel I will try to release this week I was hoping to get the original authors feedback

**Comment by MGApcDev** [comment]
@neild3r Sorry, I've been terribly busy. This looks good, approved from my end 👍 

-- Mathias

**Pull request merged**
