### PR TITLE
Add php 8 union function args and return

### PR DESCRIPTION
**Pull request by neild3r**

### CODE REVIEW

**Comment by tianyiw2013** [comment]
Please merge as soon as possible, I'm merging my branches. ^_^

**Comment by tianyiw2013** [comment]
This feature has been implemented in my pull request #175

**Comment by neild3r** [comment]
@tianyiw2013 I did it a slightly different way I took inspiration from some of the work you did but your PR covered too many things and was difficult to pick apart and merge in so have re-implemented. It was a fairly simple update anyway this one.

**Comment by shivapoudel** [comment]
@tianyiw2013 Any Gif demo for this feature would be great to understand! Can you help?

**Pull request merged**
