### PR TITLE
Fix full class names

### PR DESCRIPTION
**Pull request by tianyiw2013**
**Change Summary**:
- Fixed fully qualifies class namespace detection can be incorrect with _ #214 
- Supported fully qualifies class namespace use with bracket `use some\namespace\{ ClassA, ClassB, ... }` #122 
- Supported fully qualifies class namespace use with comma `use some\namespace\ClassA, some\namespace\ClassB, ...`

**Checks**:
* [x] `CHANGELOG.md` updated with relavent changes

### CODE REVIEW

**Comment by tianyiw2013** [comment]
Test Suite Failing
I don't know how to solve the problem. Help me @neild3r 
https://github.com/neild3r/vscode-php-docblocker/runs/4485797651?check_suite_focus=true

**Comment by neild3r** [comment]
Hmmm I'm not too sure I've had this before but re-running has always helped. This time it doesn't seem to be doing the same trick

**Comment by tianyiw2013** [comment]
lcov.info no content generated.
I studied it for a long time, but it still didn't work properly.

**Comment by tianyiw2013** [comment]
Submitted again and again, and finally passed.

**Comment by neild3r** [comment]
We definitely need to work out why it's being so inconsistent as this is frustrating. Perhaps it just needs a delay in the git hub action or something.

**Review by neild3r — CHANGES_REQUESTED** [review]
Hi @tianyiw2013,

Sorry for the delay in getting back to you on this. Happy new year and thanks for you work to date. I have a few bits of feedback.

- Would it be possible to break up the `getFullyQualifiedType` method into more methods.
- There should probably be a `getClassesFromUse` method or something similar which just works with an individual line.
- Please could we also use camelCase instead of snake_case

If you do not understand please let me know I understand english isn't your first language.

**Comment by tianyiw2013** [comment]
Thank you for your feedback. Is this OK now?

Test Suite failed again. -_-

**Comment by neild3r** [comment]
@tianyiw2013 yes this is looking much neater thank you. I will look at the test suite issue as this is not on you for whatever reason it's being inconsistent

**Review by neild3r — APPROVED** [review]

**Comment by neild3r** [comment]
@tianyiw2013 I believe I have fixed the problem with the coverage tests and have updated your branch

**Pull request merged**
